In [1]:
import tensorflow as tf
import numpy as np

# padding

In [2]:
# 初始化 5*5 数组
arr = np.array(np.arange(0,25))
arr = arr.reshape((5,5))
print(f"初始数组：\n{arr}")

初始数组：
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
# zero-padding
zero_padding = tf.pad(arr,[[1,1],[1,1]])
print(f"\n全零填充：\n{zero_padding}")

# reflect-padding
reflect_padding = tf.pad(arr,[[1,1],[1,1]],"REFLECT")
print(f"\n反射填充：\n{reflect_padding}")

# replicate-padding
replicate_padding = tf.pad(arr,[[1,1],[1,1]],"SYMMETRIC")
print(f"\n复制填充：\n{replicate_padding}")


全零填充：
[[ 0  0  0  0  0  0  0]
 [ 0  0  1  2  3  4  0]
 [ 0  5  6  7  8  9  0]
 [ 0 10 11 12 13 14  0]
 [ 0 15 16 17 18 19  0]
 [ 0 20 21 22 23 24  0]
 [ 0  0  0  0  0  0  0]]

反射填充：
[[ 6  5  6  7  8  9  8]
 [ 1  0  1  2  3  4  3]
 [ 6  5  6  7  8  9  8]
 [11 10 11 12 13 14 13]
 [16 15 16 17 18 19 18]
 [21 20 21 22 23 24 23]
 [16 15 16 17 18 19 18]]

复制填充：
[[ 0  0  1  2  3  4  4]
 [ 0  0  1  2  3  4  4]
 [ 5  5  6  7  8  9  9]
 [10 10 11 12 13 14 14]
 [15 15 16 17 18 19 19]
 [20 20 21 22 23 24 24]
 [20 20 21 22 23 24 24]]


# pooling

In [4]:
arr = np.array(np.arange(0,25))
arr = arr.reshape((5,5))
x = tf.constant(arr)
print(f"初始数组：\n{x}")

初始数组：
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
x = tf.reshape(x, [1, 5, 5, 1])

In [6]:
# 最大池化
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2),
                                           strides=(1, 1), 
                                           padding='valid')
max_pooling = max_pool_2d(x).numpy().reshape(4,4)
print(f"\n最大池化：\n{max_pooling}")

# 平均池化
ave_pool_2d = tf.keras.layers.AveragePooling2D(pool_size=(2, 2),
                                           strides=(1, 1), 
                                           padding='valid')
ave_pool_2d = max_pool_2d(x).numpy().reshape(4,4)
print(f"\n平均池化：\n{ave_pool_2d}")


最大池化：
[[ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]

平均池化：
[[ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]
