In [1]:
import tensorflow as tf
import numpy as np

In [2]:
model = tf.keras.Sequential()
# 添加Embedding层将1000维映射到64维
model.add(tf.keras.layers.Embedding(1000, 64, input_length=16))
# 编译模型
model.compile('adam', 'mse')

In [3]:
# 初始化4个列表（4句话），每个列表有16个数字（单词），每个单词的索引范围在0-1000
input_array = np.random.randint(1000, size=(4, 16))
print(f'模型输入形状：{input_array.shape}')
print(f'模型输入：{input_array}\n')
# 预测模型
output_array = model.predict(input_array)
print(f'模型输出形状：{output_array.shape}') # (32, 10, 64)
print(f'模型输出：{output_array}') # (32, 10, 64)

模型输入形状：(4, 16)
模型输入：[[294 477 537 119 550 805 537 794 360 716 273 423 974 435 390 286]
 [855 601 483 840  49 270 294 716 166 251 745 334  78 927 593 263]
 [941 247 198 919 603 934 418 102 842 606  95  30 593 504 919 315]
 [409  52 180 179 543 619 529 651 676 308 756  96 218 209 396 618]]

1/1 [==============================] - 0s 89ms/step
模型输出形状：(4, 16, 64)
模型输出：[[[-2.20002420e-02 -7.56216049e-03 -4.16862369e-02 ... -3.84299979e-02
    1.78038515e-02  3.87238748e-02]
  [ 2.67015770e-03 -1.97484493e-02 -2.34509949e-02 ... -3.22349072e-02
    2.28834040e-02 -4.02588956e-02]
  [ 2.10069455e-02 -2.41151806e-02 -4.89534624e-02 ...  3.10312994e-02
   -4.60795052e-02 -9.00172070e-03]
  ...
  [-3.92798334e-03 -4.05619517e-02 -1.36964098e-02 ...  3.47564332e-02
   -3.47970612e-02 -1.66598186e-02]
  [ 2.39309110e-02 -4.97646220e-02  2.40466259e-02 ... -3.89561877e-02
   -2.96509750e-02  3.20891850e-02]
  [ 3.36196274e-03 -1.44643895e-02 -4.51239347e-02 ... -4.69680689e-02
    9.99268144e-03  4.